name: gamechat
description: "A private low-latency real-time voice chat Android app for gamers with background service, WebRTC, and soundboard."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.6.2
  socket_io_client: ^3.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  audioplayers: ^6.1.0
  file_picker: ^10.3.3
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  flutter_foreground_task: ^6.5.0
  uuid: ^4.5.1
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
